### ISSUE TITLE
Replace benchmark for loops with while loops

### ISSUE THREAD

**Issue by Slatercody** [Whiley/WyBench#20]
This is a list of benchmarks that need for loops updated with while loops:
- <strike>008_scc</strike>
- 101_calculator
- 202_chess
- 102_conway
- 104_tictactoe
- 201_convert
- 203_jasm
- 204_raytrace

**Comment by DavePearce** [comment]
Thanks Cody.  Turns out I fixed <code>008_scc</code> today ... so I'll cross that off the list!!  A few more to go though!
