### ISSUE TITLE
Fix incorrect invariant on type day in 016_date

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#23]
In the benchmark test 016_date/main, the `next`  function fails for the following test input:

Failed Input: {day:1,year:0,month:1} Output: {day:2,year:0,month}

This causes the invariant in Date, to fail due to the invariant applied to the nominal type, day:
 `type day is (int d) where d <= 1 && d <= 31`

which should be `1 <= d` instead.

**Comment by DavePearce** [comment]
Whoops closed the wrong one before.  Yes, agreed, this is broken.  Have merged your fix --- thanks!!
