### ISSUE TITLE
Fix incorrect postcondition for compare() in 030_fractions

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#25]
In the benchmark test 030_fractions/main, the compare function fails for the following test input:

Failed Input: [{numerator:0,denominator:1}, {numerator:1,denominator:1}] Output: -1

This is valid for the first line in the postcondition 
`ensures r < 0 <==> (f1.numerator * f2.denominator) < (f2.numerator * f1.denominator)`

but invalid for the following postcondition
`ensures r > 0 <==> (f1.numerator * f2.denominator) < (f2.numerator * f1.denominator)`

Changing the invalid postcondition should fix this problem

`ensures r > 0 <==> (f1.numerator * f2.denominator) > (f2.numerator * f1.denominator)`

**Comment by DavePearce** [comment]
Oh yeah, that's obviously broken.  Nice!
