### ISSUE TITLE
Fix erroneous inputs for findMaximalMatching in 029_bipmatch

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#29]
`findMaximalMatching` function fails on the following inputs:

Failed Input: [{N1:1,N2:1,edges:[{to:0,from:0}]}] 
Failed Input: [{N1:1,N2:1,edges:[{to:0,from:0}, {to:0,from:0}]}]
Failed Input: [{N1:1,N2:1,edges:[{to:0,from:0}, {to:0,from:0}, {to:0,from:0}]}] 

Looking into the function, `findMaximalMatching` calls `find` which then calls `match`. 
The `match` causes the error as the precondition of `match` fails on the precondition:

`requires 0 <= m.left[from] && m.left[from] < |m.right|`

As `m.left` is [-1] . 
I think this is something to do with the left and right array being set to UNMATCHED (-1) in the `Matching()` without being changed.

Note these inputs pass:

INPUT: [{N1:1,N2:1,edges:[{to:0,from:0}]}]
INPUT: [{N1:1,N2:2,edges:[{to:0,from:0}]}]
INPUT: [{N1:1,N2:2,edges:[{to:0,from:0}, {to:1,from:0}]}]

**Comment by DavePearce** [comment]
Ok, I need to dig into this a bit I think.

**Comment by DavePearce** [comment]
Yeah, this algorithm is not super well tested I think.  Right, there's not even a `build.xml` file.

**Comment by DavePearce** [comment]
Have spent an hour or so on this now.  I have corrected a bug with the definition of `Graph` which was not enforcing the bipartite invariant properly.  It now reads:

```
type Graph is {
    int N1,      // size of first partition
    int N2,      // size of second partition
    edge[] edges // edges in graph
}
// Partitions are valid
where N1 >= 0 && N2 >= 0
// All edges are from a valid vertex
where all { i in 0..|edges| | 0 <= edges[i].from && edges[i].from < N1 }
// All edges are to a valid vertex
where all { i in 0..|edges| | N1 <= edges[i].to && edges[i].to < (N1+N2) }
```

In particular, the latter `all` quantifier ranges from `N1` rather than `0` as before.  This I think helps as Janice's counterexample above is not a bipartite graph (hence, perhaps why it fails).  However, the test case I've added in the `main` method is still failing for reasons unknown.  Further investigation is required, though perhaps not today.

**Comment by DavePearce** [comment]
Have now got it successfully working for my small example in the `main` method.  Probably could do more testing, but it'll do for now.

@JC626 Can you run it again now?

**Comment by JC626** [comment]
Looks like `findMaximalMatching` is working now when running small tests.

Looking at the failing main method, I've managed to trace the error to this statement:

`int tor = m.right[e.to]`

Seems that it is trying to access  `m.right` which is [-1, -1] at the index 3 as `e.to` is 3.

The current frame is:

`{g={N1:1,N2:1,edges:[{to:3,from:0}, {to:3,from:1}, {to:4,from:1}, {to:5,from:2}, {to:4,from:2}]}, from=0, e={to:3,from:0}, m={left:[-1],graph:{N1:1,N2:1,edges:[{to:3,from:0}, {to:3,from:1}, {to:4,from:1}, {to:5,from:2}, {to:4,from:2}]},right:[-1, -1]}, visited=[true], i=0}`

**Comment by DavePearce** [comment]
Argh, such a stupid mistake.  Doh!!!  Thanks and very well spotted!!  Corrected now and this issue is finally closed :)
