### ISSUE TITLE
Fix NegativeArrayException on 018_heap

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#35]
In `018_heap/main` a NegativeArrayException can occur for:

```
type Heap is ({
    int[] data,
    int length
} h)
```

This is due to the length of the Heap being less than zero.
The length of the Heap could also be outside of the bounds of the array, `data`. 
Therefore, type constraints would need to be added to ensure the length is within the array's bounds.

**Comment by DavePearce** [comment]
Nice!
