### ISSUE TITLE
025_tries errors

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#39]
A bunch of errors occurred when executing tests for 025_tries. Tests used the integer limits between 0 to 5.

* `add(Trie trie, ascii::string str)` 
  * Execution error likely due to `add(Trie trie, nat state, ascii::string str, nat index)` precondition or type constraint failing.
* `add(Trie trie, nat state, ascii::string str, nat index)` 
  * Type constraint is failing for Trie for some inputs.
* `contains(Trie trie, int state, ascii::string str, int index)`
  *  Probably need to check the `index` is within the length of the `str`.

Okay 
* `contains(Trie trie, ascii::string str)`
* `main`

Attached is the output from testing. 

[025_tries_main_result.txt](https://github.com/Whiley/WyBench/files/2261856/025_tries_main_result.txt)

**Comment by DavePearce** [comment]
Am closing this now.  There have been a whole load of fixes this benchmark and others, and I'm not aware of any problems with it right now.
