### ISSUE TITLE
ArrayIndexOutOfBounds for 008_scc visit()

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#40]
For `visit(int v, State s)`, the function throws an ArrayIndexOutOfBounds for some inputs.

Failed input: [0, {graph:[],index:0,stack:{items:[],length:0},cindex:0,rindex:[],visited:[],inComponent:[]}]

Due to `v` used as an index to access various arrays within `State`.

**Comment by DavePearce** [comment]
Be good if you can recheck my changes and make sure still good.
